name: wistia_video_player
version: 1.0.1
description: "Simple Flutter widget for embedding Wistia videos with full customization support"
homepage: https://github.com/booooohdan/wistia_video_player
repository: https://github.com/booooohdan/wistia_video_player
documentation: https://github.com/booooohdan/wistia_video_player

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  webview_flutter: ^4.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true